cargo-features = ["edition2021"]

[package]
name = "bitcoin_hfuzz_serialize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5"
bitcoin = "0.27"
byteorder = "1"
